"""battles

Revision ID: d7538027394a
Revises: e1b7a3673b5e
Create Date: 2019-04-19 10:34:48.189595

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'd7538027394a'
down_revision = 'e1b7a3673b5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('battles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_player_id', sa.String(), nullable=True),
    sa.Column('to_player_id', sa.String(), nullable=True),
    sa.Column('medals', sa.Integer(), nullable=False),
    sa.Column('win', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['from_player_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['to_player_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('battles')
    # ### end Alembic commands ###
