"""groups

Revision ID: e1b7a3673b5e
Revises: b4ee2e60c6c9
Create Date: 2019-04-18 19:58:57.301381

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'e1b7a3673b5e'
down_revision = 'b4ee2e60c6c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('group_num', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'group_num')
    # ### end Alembic commands ###
